# Generated by Django 3.1.2 on 2021-11-10 03:11

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_name', models.CharField(max_length=100, unique=True)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('storage_shelf', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'boxes',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('paper_size', models.CharField(choices=[('LETTER', 'Letter')], default='Letter', max_length=15)),
                ('top_margin', models.FloatField()),
                ('left_margin', models.FloatField()),
                ('label_width', models.FloatField()),
                ('label_height', models.FloatField()),
                ('columns', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField()),
                ('row_margin', models.FloatField()),
                ('col_margin', models.FloatField()),
                ('top_padding', models.FloatField()),
                ('left_padding', models.FloatField()),
                ('max_chars', models.PositiveIntegerField(default=25)),
                ('font_size', models.FloatField(default=7)),
                ('qr_size', models.FloatField(default=12)),
                ('line_spacing', models.FloatField(default=2.3)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('investigator', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, unique=True)),
                ('box_position', models.IntegerField(blank=True, null=True)),
                ('collection_status', models.CharField(choices=[('Collected', 'Collected'), ('Absent', 'Absent'), ('Refused', 'Refused'), ('Pending', 'Pending'), ('Withdrew', 'Withdrew')], default='Pending', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.box')),
                ('collection_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.event')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.location')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('protocol', models.TextField(blank=True, null=True)),
                ('detects', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replicate', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Pending', 'Pending'), ('Unknown', 'Unknown'), ('Inconclusive', 'Inconclusive')], default='Pending', max_length=15)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('researcher', models.ManyToManyField(blank=True, to='lims.Researcher')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.test')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ui', models.CharField(blank=True, max_length=6, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('consent_status', models.CharField(choices=[('Consented', 'Consented'), ('Not Consented', 'Not Consented'), ('Withdrawn', 'Withdrawn')], default='Consented', max_length=15)),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('withdrawn_date', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True)),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, choices=[('K', 'K'), ('NH', 'NH'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gardian_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vaccine_status', models.CharField(blank=True, choices=[('FULL', 'Full'), ('PARTIAL', 'Partial'), ('BOOSTED', 'Boosted'), ('NO', 'None')], max_length=10, null=True)),
                ('dose_1', models.DateField(blank=True, null=True)),
                ('dose_2', models.DateField(blank=True, null=True)),
                ('dose_3', models.DateField(blank=True, null=True)),
                ('prior_covid', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Has subject been infected with COVID-19 prior to study', max_length=10, null=True)),
                ('pneumococcal_vaccine', models.CharField(blank=True, choices=[('FULL', 'Full'), ('PARTIAL', 'Partial'), ('BOOSTED', 'Boosted'), ('NO', 'None')], max_length=10, null=True)),
                ('pneumococcal_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.location')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.subject'),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('notification_status', models.CharField(choices=[('Notified', 'Notified'), ('Not Notified', 'Not Notified'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('box_position', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.box')),
                ('pools', models.ManyToManyField(blank=True, to='lims.Pool')),
                ('samples', models.ManyToManyField(blank=True, to='lims.Sample')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.project'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(to='lims.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='researcher',
            field=models.ManyToManyField(blank=True, to='lims.Researcher'),
        ),
    ]
