# Generated by Django 3.1.2 on 2021-11-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='notes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
