# Generated by Django 3.1.2 on 2021-10-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(to='lims.Location'),
        ),
    ]
