# Generated by Django 3.1.2 on 2021-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20211023_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
