# Generated by Django 3.1.2 on 2021-11-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_subject_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ('-created_on',), 'verbose_name_plural': 'boxes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ('-created_on', 'status')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-created_on', 'collection_event', 'location')},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('last_name', 'first_name')},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ('-created_on',)},
        ),
    ]
