# Generated by Django 3.1.2 on 2021-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20211115_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('-created_on', 'collection_event', 'location', 'sample_type')},
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('Nasal', 'Nasal'), ('Oral', 'Oral')], default='Nasal', max_length=15),
        ),
    ]
