# Generated by Django 3.1.2 on 2021-11-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20211117_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ('subject', 'collection_event', 'location', 'sample_type')},
        ),
    ]
