# Generated by Django 3.1.2 on 2021-10-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20211027_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Pending', 'Pending')], default='Pending', max_length=15)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pools', models.ManyToManyField(to='lims.Pool')),
                ('samples', models.ManyToManyField(to='lims.Location')),
            ],
        ),
    ]
