# Generated by Django 3.1.2 on 2021-11-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_auto_20211117_1221'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique name'),
        ),
    ]
