# Generated by Django 3.1.2 on 2021-10-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20211027_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='samples',
            field=models.ManyToManyField(to='lims.Sample'),
        ),
    ]
