# Generated by Django 3.1.2 on 2021-10-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_auto_20211027_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='pools',
            field=models.ManyToManyField(blank=True, to='lims.Pool'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='samples',
            field=models.ManyToManyField(blank=True, to='lims.Sample'),
        ),
    ]
