# Generated by Django 3.1.2 on 2021-11-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_auto_20211101_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'boxes'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='researcher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('-created_on',)},
        ),
    ]
