# Generated by Django 3.1.2 on 2022-02-22 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_auto_20220114_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolbox',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='samplebox',
            name='positions',
        ),
        migrations.AddField(
            model_name='poolboxposition',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='lims.poolbox'),
        ),
        migrations.AddField(
            model_name='sampleboxposition',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='lims.samplebox'),
        ),
        migrations.AlterField(
            model_name='poolbox',
            name='size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='poolboxposition',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_pools', to='lims.pool'),
        ),
        migrations.AlterField(
            model_name='samplebox',
            name='size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='sampleboxposition',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_samples', to='lims.sample'),
        ),
    ]
