# Generated by Django 3.1.2 on 2022-05-11 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_event_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='second_booster',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='second_booster_month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='second_booster_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1980)]),
        ),
    ]
