# Generated by Django 3.1.2 on 2021-11-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_auto_20211101_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sheet_length', models.PositiveIntegerField()),
                ('sheet_width', models.PositiveIntegerField()),
                ('top_margin', models.PositiveIntegerField()),
                ('bottom_margin', models.PositiveIntegerField()),
                ('left_margin', models.PositiveIntegerField()),
                ('right_margin', models.PositiveIntegerField()),
                ('label_width', models.PositiveIntegerField()),
                ('label_height', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField()),
                ('row_margin', models.PositiveIntegerField()),
                ('col_margin', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.project'),
        ),
    ]
