# Generated by Django 3.1.2 on 2022-06-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_auto_20220511_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='continue_22_23_year',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
