# Generated by Django 3.1.2 on 2022-08-14 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_subject_continue_22_23_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='consent_status',
            field=models.CharField(choices=[('Consented', 'Consented'), ('Not Consented', 'Not Consented'), ('Withdrawn', 'Withdrawn'), ('Inactive', 'Inactive')], default='Consented', max_length=15),
        ),
    ]
