# Generated by Django 3.1.2 on 2021-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_auto_20211101_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='bottom_margin',
        ),
        migrations.RemoveField(
            model_name='label',
            name='right_margin',
        ),
        migrations.RemoveField(
            model_name='label',
            name='sheet_length',
        ),
        migrations.AddField(
            model_name='label',
            name='sheet_height',
            field=models.FloatField(default=279.4),
        ),
        migrations.AlterField(
            model_name='label',
            name='col_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='left_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='left_padding',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='row_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='sheet_width',
            field=models.FloatField(default=215.9),
        ),
        migrations.AlterField(
            model_name='label',
            name='top_margin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='top_padding',
            field=models.FloatField(),
        ),
    ]
