# Generated by Django 3.1.2 on 2022-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_auto_20220814_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('LTCF', 'LTCF'), ('School', 'School')], default='School', max_length=8),
        ),
        migrations.AddField(
            model_name='location',
            name='school_level',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Middle', 'Middle'), ('Elementary', 'Elementary')], max_length=16, null=True),
        ),
    ]
