# Generated by Django 3.1.2 on 2021-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_auto_20211101_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='font_size',
            field=models.FloatField(default=7),
        ),
        migrations.AddField(
            model_name='label',
            name='max_chars',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
