# Generated by Django 3.1.2 on 2022-12-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_auto_20221130_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_vaccinated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
