# Generated by Django 3.1.2 on 2021-11-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_auto_20211101_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='sheet_height',
        ),
        migrations.RemoveField(
            model_name='label',
            name='sheet_width',
        ),
        migrations.AddField(
            model_name='label',
            name='paper_size',
            field=models.CharField(choices=[('Letter', 'LETTER')], default='Letter', max_length=15),
        ),
    ]
