# Generated by Django 3.1.2 on 2022-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_subject_is_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='subject_is_vax',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
