# Generated by Django 3.1.2 on 2021-11-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_auto_20211101_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='line_spacing',
            field=models.FloatField(default=2.3),
        ),
        migrations.AddField(
            model_name='label',
            name='qr_size',
            field=models.FloatField(default=12),
        ),
        migrations.AlterField(
            model_name='label',
            name='paper_size',
            field=models.CharField(choices=[('LETTER', 'Letter')], default='Letter', max_length=15),
        ),
    ]
