# Generated by Django 3.1.2 on 2023-09-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0017_sample_subject_is_vax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('run_id', models.CharField(blank=True, max_length=100, null=True)),
                ('protocol', models.TextField(blank=True, null=True)),
                ('targets', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('samples', models.ManyToManyField(blank=True, to='lims.Sample')),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
