# Generated by Django 3.1.2 on 2021-11-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_auto_20211102_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='researcher',
        ),
        migrations.AddField(
            model_name='event',
            name='researcher',
            field=models.ManyToManyField(blank=True, null=True, to='lims.Researcher'),
        ),
    ]
