# Generated by Django 3.1.2 on 2023-09-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_sequencing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencing',
            name='pools',
            field=models.ManyToManyField(blank=True, to='lims.Pool'),
        ),
    ]
