# Generated by Django 3.1.2 on 2021-11-03 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0020_auto_20211102_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='results',
        ),
        migrations.AddField(
            model_name='testresult',
            name='sample',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.sample'),
        ),
    ]
