# Generated by Django 3.1.2 on 2021-11-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0024_auto_20211102_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='name',
        ),
        migrations.AddField(
            model_name='testresult',
            name='rep',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
