# Generated by Django 3.1.2 on 2021-10-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='covid',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], help_text='Has subject been infected with COVID-19 prior to study', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='vaccine_status',
            field=models.CharField(blank=True, choices=[('FULL', 'Full'), ('PARTIAL', 'Partial'), ('NO', 'None')], max_length=10, null=True),
        ),
    ]
